title: Stainless
description: Verification framework for a subset of the Scala programming language.

baseurl: ""
url: ""

# Build settings
markdown: kramdown
# theme: jekyll-theme-tactile
theme: jekyll-theme-minimal
plugins: []

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
